name: Deploy to Vercel
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        working-directory: /c:/Users/mejia/Desktop/githubActions/test_actions/test_app
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.1.1
        with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
