name: test deply
on: 
    push:
      branches:
        - main
    
jobs: 
  Explore-github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/chockout@v2
      - uses: actions/setup-react@v2
      - name: install packages
        run: npm install
      - name: build
        run: npm run build
      - name: Vercel Action
        uses: amondnet/vercel-action@v25.1.1
            
